import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',args:['--enable-unsafe-swiftshader']});
const errors=[];
const saved={found:['books','drawer','plant','sofa','music'],wished:false,puzzles:{solved:['books','drawer','plant','sofa','music'],items:['record','wateringCan','key'],clues:['postcard','clock','record','key']}};
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:5173/');const canvas=page.locator('canvas'),app=page.locator('main');await canvas.waitFor();await page.evaluate(()=>document.fonts.ready);
 async function enter(){await page.getByRole('button',{name:'走进小屋',exact:true}).click();await page.waitForTimeout(250);await page.evaluate(()=>{if(document.pointerLockElement)document.exitPointerLock();});await page.waitForTimeout(150);}
 const pose=async()=>JSON.parse(await canvas.getAttribute('data-pose'));
 async function look(yaw,pitch=0){const p=await pose();const delta=Math.atan2(Math.sin(yaw-p.yaw),Math.cos(yaw-p.yaw));const dx=-delta/.0025,dy=-(pitch-p.pitch)/.0025,n=Math.max(1,Math.ceil(Math.max(Math.abs(dx),Math.abs(dy))/200));for(let i=0;i<n;i++){await page.mouse.move(760,440);await page.mouse.down();await page.mouse.move(760+dx/n,440+dy/n,{steps:2});await page.mouse.up();}await page.waitForTimeout(200);}
 async function approach(){await enter();await canvas.focus();await page.keyboard.down('w');await page.waitForTimeout(1100);await page.keyboard.up('w');await page.waitForTimeout(250);}
 await enter();const p=await pose();await look(Math.atan2(p.x+.43,p.z-5.01));
 await page.getByRole('button',{name:'关闭室内灯光',exact:true}).click();await page.waitForTimeout(1500);assert.equal(await app.getAttribute('data-lights-on'),'false');assert.equal(await canvas.getAttribute('data-candle-lit'),'false');
 await page.screenshot({path:'test-results/switch-off.png'});
 await look(.27,-.04);await page.waitForTimeout(400);await page.screenshot({path:'test-results/moonlit-room.png'});const prompt=await page.locator('.interaction-prompt').boundingBox();assert(prompt.x<70&&prompt.y>700,'Desktop prompt belongs in the lower left');await look(Math.atan2(p.x+.43,p.z-5.01));
 await page.getByRole('button',{name:'打开室内灯光',exact:true}).click();assert.equal(await app.getAttribute('data-lights-on'),'true');
 await page.reload();await canvas.waitFor();await approach();await page.locator('.cake-hotspot').click();assert.equal(await app.getAttribute('data-revealing'),'false');assert.equal(await canvas.getAttribute('data-cake-opened'),'false');assert.equal(await app.getAttribute('data-lights-on'),'true');
 await page.screenshot({path:'test-results/cake-covered.png'});
 await page.evaluate(s=>localStorage.setItem('birthday-little-room-v2',JSON.stringify(s)),saved);await page.reload();await canvas.waitFor();await approach();
 await page.locator('.cake-hotspot').click();assert.equal(await app.getAttribute('data-revealing'),'true');const before=await pose();await canvas.focus();await page.keyboard.down('w');await page.waitForTimeout(900);await page.keyboard.up('w');const after=await pose();assert(Math.hypot(after.x-before.x,after.z-before.z)<.001);
 await page.screenshot({path:'test-results/cake-reveal-mid.png'});
 await page.getByRole('dialog',{name:'许一个生日愿望'}).waitFor();await page.waitForTimeout(500);assert.equal(await canvas.getAttribute('data-cake-opened'),'true');assert.equal(await app.getAttribute('data-revealing'),'false');assert.equal(await app.getAttribute('data-lights-on'),'false');assert.equal(await canvas.getAttribute('data-candle-lit'),'true');assert(Number(await canvas.getAttribute('data-light-level'))<.001);assert.equal(await app.getAttribute('data-music-playing'),'true');
 await page.screenshot({path:'test-results/candle-wish.png'});
 await page.keyboard.press('Escape');await canvas.focus();await page.keyboard.down('d');await page.waitForTimeout(350);await page.keyboard.up('d');await page.waitForTimeout(150);const moving=await pose();assert(Math.hypot(moving.x-after.x,moving.z-after.z)>.1);
 await page.reload();await canvas.waitFor();assert.equal(await canvas.getAttribute('data-cake-opened'),'true');await approach();await page.locator('.cake-hotspot').click();await page.getByRole('dialog',{name:'许一个生日愿望'}).waitFor();await page.getByRole('button',{name:'许好啦，吹灭蜡烛'}).click();await page.waitForTimeout(1000);assert.equal(await app.getAttribute('data-lights-on'),'true');assert.equal(await canvas.getAttribute('data-candle-lit'),'false');
 await page.getByRole('button',{name:'再在小屋待一会儿'}).click();await page.getByRole('button',{name:/口袋里的心意/}).click();await page.getByRole('button',{name:'重新探索',exact:true}).click();await page.getByRole('button',{name:'重新开始',exact:true}).click();assert.equal(await canvas.getAttribute('data-cake-opened'),'false');assert.equal(await app.getAttribute('data-lights-on'),'true');assert.equal(await app.getAttribute('data-music-playing'),'false');
 const mobile=await browser.newPage({viewport:{width:844,height:390},isMobile:true,hasTouch:true,reducedMotion:'reduce'});mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto('http://127.0.0.1:5173/');await mobile.evaluate(s=>localStorage.setItem('birthday-little-room-v2',JSON.stringify(s)),saved);await mobile.reload();await mobile.locator('canvas').waitFor();await mobile.getByRole('button',{name:'走进小屋',exact:true}).tap();await mobile.locator('canvas').focus();await mobile.keyboard.down('w');await mobile.waitForTimeout(1100);await mobile.keyboard.up('w');await mobile.waitForTimeout(250);await mobile.locator('.cake-hotspot').tap();await mobile.getByRole('dialog',{name:'许一个生日愿望'}).waitFor();await mobile.evaluate(()=>document.fonts.ready);await mobile.screenshot({path:'test-results/candle-wish-mobile.png'});assert.equal(await mobile.evaluate(()=>document.body.scrollWidth>innerWidth),false);await mobile.getByRole('button',{name:'许好啦，吹灭蜡烛'}).tap();assert.equal(await mobile.locator('main').getAttribute('data-lights-on'),'true');
 await mobile.getByRole('button',{name:'再在小屋待一会儿'}).tap();const mobilePrompt=await mobile.locator('.interaction-prompt').boundingBox(),mobilePad=await mobile.locator('.touch-controls').boundingBox();assert(mobilePrompt.x<40&&mobilePrompt.y>190&&mobilePrompt.y+mobilePrompt.height<mobilePad.y,'Mobile prompt is in the lower left above the controls');await mobile.screenshot({path:'test-results/prompt-mobile.png'});
 assert.deepEqual(errors,[]);console.log('PASS: physical light switch off/on, opaque locked cover, reveal animation and movement lock, moonlit room and candle wish scene, lower-left desktop/mobile prompts, audio, persisted opening, blow-out restores room lights, reset, mobile and reduced motion.');
}finally{await browser.close();}
